### ISSUE TITLE
Bot won't launch

### ISSUE THREAD

**Issue by Czechball** [ButternCream/Spotty#1]
Hello,
When I try to start the bot, I get the following output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 580, in _load_from_module_spec
    setup(self)
  File "/home/czechball/Spotty/cogs/commands/owner.py", line 58, in setup
    bot.add_cog(Owner(bot))
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 480, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 140, in load_extensions
    bot.load_extension(extension)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 625, in load_extension
    self._load_from_module_spec(lib, name)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 584, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.commands.owner' raised an error: TypeError: cogs must derive from Cog
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 580, in _load_from_module_spec
    setup(self)
  File "/home/czechball/Spotty/cogs/commands/admin.py", line 110, in setup
    bot.add_cog(Admin(bot))
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 480, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 140, in load_extensions
    bot.load_extension(extension)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 625, in load_extension
    self._load_from_module_spec(lib, name)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 584, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.commands.admin' raised an error: TypeError: cogs must derive from Cog
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 580, in _load_from_module_spec
    setup(self)
  File "/home/czechball/Spotty/cogs/commands/everyone.py", line 85, in setup
    bot.add_cog(Everyone(bot))
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 480, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 140, in load_extensions
    bot.load_extension(extension)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 625, in load_extension
    self._load_from_module_spec(lib, name)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 584, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.commands.everyone' raised an error: TypeError: cogs must derive from Cog
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 580, in _load_from_module_spec
    setup(self)
  File "/home/czechball/Spotty/cogs/overrides.py", line 22, in setup
    bot.add_cog(Overrides(bot))
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 480, in add_cog
    raise TypeError('cogs must derive from Cog')
TypeError: cogs must derive from Cog

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 140, in load_extensions
    bot.load_extension(extension)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 625, in load_extension
    self._load_from_module_spec(lib, name)
  File "/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 584, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.overrides' raised an error: TypeError: cogs must derive from Cog
^C^CTraceback (most recent call last):
  File "bot.py", line 149, in <module>
    bot.run(spotty_token)
  File "/usr/lib/python3.8/site-packages/discord/client.py", line 595, in run
    _cleanup_loop(loop)
  File "/usr/lib/python3.8/site-packages/discord/client.py", line 92, in _cleanup_loop
    _cancel_tasks(loop)
  File "/usr/lib/python3.8/site-packages/discord/client.py", line 77, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*tasks, loop=loop, return_exceptions=True))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 614, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

My system: Python 3.8.6, Arch Linux 5.7.10-arch1-1

**Comment by ButternCream** [comment]
@Czechball 
This seems to be due to the code being 2 years old and not up to date with
https://github.com/Rapptz/discord.py. The cog class I wrote needs to extend `commands.Cog` it seems like according to the [docs](https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html?highlight=cogs)

**Comment by ButternCream** [comment]
Updated
